-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE blocks (
	cid text NOT NULL,
	size integer NOT NULL,
	created timestamp with time zone NOT NULL,
	data bytea,
	deleted boolean NOT NULL,
	pack_object text NOT NULL,
	pack_offset integer NOT NULL,
	pack_status integer NOT NULL,
	PRIMARY KEY ( cid )
);
